export const categories = [
  {main: {title: "Action & adventure", id: 1365}, 
  sub: [
    {title: 'Military action & adventure' , id: 2125},
    {title: 'Action comedies' , id: 43040},  
    {title: 'Spy action & adventure', id: 10702},
    {title: 'Crime action & adventure', id: 9584},
    {title: 'Action sf & fantasy', id: 1568},
    {title: 'Action thrillers', id: 43048},
    {title: 'Asian action movies', id: 77232},
    {title: 'Adventures', id: 7442},
    {title: 'Comic book and superhero movies', id: 10118},
    {title: 'Martial arts movies', id: 8985},
    {title: 'Foreign action & adventure', id: 11828},
    {title: 'Westerns', id: 7700},
    {title: 'Hijacking movies', id: 20541},
    {title: 'Classic Action & Adventure', id: 46576}
]},
{main: {title: "Classic Movies", id: 31574}, 
  sub: [
    {title: 'Classic action & adventure' , id: 46576},
    {title: 'Classic comedies' , id: 31694},  
    {title: 'Classic dramas', id: 29809},
    {title: 'Classic musical comedy', id: 32392},
    {title: 'Classic romantic movies', id: 31273},
    {title: 'Classic SF & fantasy', id: 47147},
    {title: 'Classic thrillers', id: 46588},
    {title: 'Classic war movies', id: 48744},
    {title: 'Classic TV shows', id: 46553},
    {title: 'Classic westerns', id: 47465},
    {title: 'Film Noir', id: 7687},
    {title: 'Epics', id: 52858},
    {title: 'Silent Movies', id: 53310},
]},
{main: {title: "Comedies", id: 6548}, 
  sub: [
    {title: 'Animes comedies' , id: 9302},
    {title: 'Slapstick comedies' , id: 10256},  
    {title: 'Horror comedies', id: 89585},
    {title: 'Dark comedies', id: 869},
    {title: 'Musicals comedies', id: 13335},
    {title: 'Political comedies', id: 2700},
    {title: 'Sports comedies', id: 5286},
    {title: 'Foreign Comedies', id: 4426},
    {title: 'Late Night Comedies', id: 1402},
    {title: 'Mockumentaries', id: 26},
    {title: 'Screwball Comedies', id: 9702},
    {title: 'Stand-up Comedy', id: 4922},
    {title: 'Satires', id: 53310},
    {title: 'Romantic Comedies', id: 5475},
]},
{main: {title: "Dramas", id: 5763}, 
  sub: [
    {title: 'Biographical dramas' , id: 3179},
    {title: 'Dramas based on books' , id: 4961},  
    {title: 'Dramas based on real life', id: 3653},
    {title: 'LGBT Dramas', id: 500},
    {title: 'Crime dramas', id: 6889},
    {title: 'Political Dramas', id: 6616},
    {title: 'Romantical dramas', id: 1255},
    {title: 'Social issues dramas', id: 3947},
    {title: 'Army dramas', id: 11},
    {title: 'Sports dramas', id: 7243},
    {title: 'Showbiz dramas', id: 5012},
]},
{main: {title: "Horror movies", id: 8711}, 
  sub: [
    {title: 'Deep sea horror movies' , id: 45028},
    {title: 'Vampire horror movies' , id: 75804},  
    {title: 'Werewolf horror movies', id: 75930},
    {title: 'Zombie horror movies', id: 75405},
    {title: 'Satanic stories', id: 6998},
    {title: 'Teen screams', id: 52147},
    {title: 'Supernatural horror movies', id: 42023},
    {title: 'Slasher and serial killer movies', id: 8646},
    {title: 'Monster movies', id: 947},
    {title: 'Horror comedy', id: 89585},
    {title: 'Foreign horror movies', id: 8654},
    {title: 'Cult horror movies', id: 10944},
]},
{main: {title: "Romantic movies", id: 8883}, 
  sub: [
    {title: 'Romantic Comedies' , id: 5475},
    {title: 'Romantic favorites' , id: 502675},  
    {title: 'Romantic foreign movies', id: 7153},
    {title: 'Steamy romantic movies', id: 35800},
    {title: 'Quirky romance', id: 36103},
    {title: 'Romantic independent movies', id: 9916},
    {title: 'Romantic dramas', id: 1255},
    {title: 'Classic romantic movies', id: 31273},
]},
{main: {title: "Sci - Fi & Fantasy", id: 1492}, 
  sub: [
    {title: 'Alien Sci - Fi' , id: 3327},
    {title: 'Sci - Fi adventure' , id: 6926},  
    {title: 'Sci - Fi dramas', id: 3916},
    {title: 'Sci - Fi thrillers', id: 11014},
    {title: 'Action Sci - Fi & fantasy', id: 1568},
    {title: 'Classic Sci - Fi & fantasy', id: 47147},
    {title: 'Cult Sci - Fi & fantasy', id: 4734},
    {title: 'Fantasy movies', id: 9744},
    {title: 'Sci - Fi horror movies', id: 1694},
    {title: 'Foreign Sci - Fi & fantasy', id: 6485},
]},
{main: {title: "Sports movies", id: 4370}, 
  sub: [
    {title: 'Martial arts movies' , id: 8985},
    {title: 'Baseball movies' , id: 12339},  
    {title: 'Basketball movies', id: 12762},
    {title: 'Martial arts, boxing & wrestling', id: 6695},
    {title: 'Soccer movies', id: 12549},
    {title: 'Football movies', id: 12803},
    {title: 'Sports comedies', id: 5286},
    {title: 'Sports documentaries', id: 180},
    {title: 'Sports dramas', id: 12443},
    {title: 'Boxing movies', id: 6485},
    {title: 'Sports & Fitness', id: 9327},
]},
{main: {title: "Thrillers", id: 8933}, 
  sub: [
    {title: 'Spy thrillers' , id: 9147},
    {title: 'Crime thrillers' , id: 10499},  
    {title: 'Political thrillers', id: 10504},
    {title: 'Psychological thrillers', id: 5505},
    {title: 'Sci-Fi thrillers', id: 11014},
    {title: 'Steamy thrillers', id: 972},
    {title: 'Action thrillers', id: 43048},
    {title: 'Classic thrillers', id: 46588},
    {title: 'Foreign thrillers', id: 10306},
    {title: 'Independent thrillers', id: 3269},
    {title: 'Gangster movies', id: 31851},
    {title: 'Mysteries', id: 9994},
    {title: 'Supernatural thrillers', id: 11140},
]},
{main: {title: "Documentaries", id: 6839}, 
  sub: [
    {title: 'Biographical documentaries' , id: 3652},
    {title: 'Historical documentaries' , id: 5349},  
    {title: 'Music & concert documentaries', id: 90361},
    {title: 'Crime documentaries', id: 9875},
    {title: 'Political documentaries', id: 7018},
    {title: 'Science & navature documentaries', id: 2595},
    {title: 'Social & cultural documentaries', id: 3675},
    {title: 'Documentaires spirituels', id: 2760},
    {title: 'Military documentaries', id: 4006},
    {title: 'Sports documentaries', id: 180},
    {title: 'Travel & adventure documentaries', id: 1159},
    {title: 'Foreign documentaries', id: 5161},
    {title: 'Religious documentaries', id: 10005},
]},
{main: {title: "TV Show", id: 83}, 
  sub: [
    {title: 'Food & travel' , id: 72436},
    {title: 'Science & nature' , id: 52780},  
    {title: 'British TV Shows', id: 52117},
    {title: 'Classic TV shows', id: 46553},
    {title: 'Crime TV shows', id: 26146},
    {title: 'Cult TV shows', id: 74652},
    {title: 'Kids\' TV', id: 27346},
    {title: 'Korean TV shows', id: 67879},
    {title: 'Miniseries', id: 4814},
    {title: 'Military TV shows', id: 25804},
    {title: 'TV action & adventure', id: 10673},
    {title: 'TV comedies', id: 10375},
    {title: 'TV documentaries', id: 10105},
    {title: 'TV dramas', id: 11714},
    {title: 'TV horror', id: 83059},
    {title: 'TV mysteries', id: 4366},
    {title: 'TV Sci-Fi & fantasy', id: 1372},
    {title: 'Reality TV', id: 9833},
]},
{main: {title: "Teen TV shows", id: 60951}, 
  sub: [
    {title: 'Teen comedies' , id: 3519},
    {title: 'Teen dramas' , id: 9299},  
    {title: 'Teen screams', id: 52147},
]},
{main: {title: "Children & family movies", id: 783}, 
  sub: [
    {title: 'Disney' , id: 67673},
    {title: 'Education for kids' , id: 10659},  
    {title: 'Movies for ages 0 to 2', id: 6796},
    {title: 'Movies for ages 2 to 4' , id: 6218},
    {title: 'Movies for ages 5 to 7' , id: 5455},
    {title: 'Movies for ages 8 to 10' , id: 561},
    {title: 'Movies for ages 11 to 12' , id: 6962},
    {title: 'Movies based on children\'s books' , id: 10056},
    {title: 'Family features' , id: 51056},
    {title: 'TV cartoons' , id: 11177},
    {title: 'Kids TV' , id: 27346},
    {title: 'Kids Music' , id: 52843},
    {title: 'Animal tales' , id: 5507},
]},
{main: {title: "Anime", id: 7424}, 
  sub: [
    {title: 'Anime action' , id: 2653},
    {title: 'Anime dramas' , id: 452},
    {title: 'Adult animation' , id: 11881},
    {title: 'Animal tales' , id: 5507},
    {title: 'Anime fantasy' , id: 11146},
    {title: 'Anime features' , id: 3063},
    {title: 'Anime horror' , id: 10695},
    {title: 'Anime Sci-Fi' , id: 2729},
    {title: 'Anime series' , id: 6721},
    {title: 'Anime comedies' , id: 9302},
]},
{main: {title: "Independent movies", id: 7077}, 
  sub: [
    {title: 'Independent action & adventure' , id: 11804},
    {title: 'Independent comedies' , id: 4195},
    {title: 'Independent dramas' , id: 384},
    {title: 'Romantic independent movies' , id: 9916},
    {title: 'Independent thrillers' , id: 3269},
    {title: 'Experimental movies' , id: 11079},
]},
{main: {title: "Foreign movies", id: 7462}, 
  sub: [
    {title: 'Foreign action & adventure' , id: 11828},
    {title: 'Classic Foreign Movies' , id: 32473},
    {title: 'Foreign comedies' , id: 4426},
    {title: 'Foreign documentaries' , id: 5161},
    {title: 'Foreign dramas' , id: 2150},
    {title: 'Foreign gay & lesbian movies' , id: 8243},
    {title: 'Foreign horror movies' , id: 8654},
    {title: 'Foreign Sci-Fi & fantasy' , id: 6485},
    {title: 'Foreign thrillers' , id: 10306},
    {title: 'Romantic foreign movies' , id: 7153},
    {title: 'Asian action movies' , id: 77232},
    {title: 'German movies' , id: 58886},
    {title: 'Latin american movies' , id: 1613},
    {title: 'African Movies' , id: 3761},
    {title: 'British movies' , id: 10757},
    {title: 'Australian movies' , id: 5230},
    {title: 'Belgian movies' , id: 262},
    {title: 'Chinese movies' , id: 3960},
    {title: 'Korean movies' , id: 5685},
    {title: 'Spanish movies' , id: 58741},
    {title: 'French movies' , id: 58807},
    {title: 'Greek movies' , id: 61115},
    {title: 'Indian movies' , id: 10463},
    {title: 'Irish movies' , id: 58750},
    {title: 'Italian Movies' , id: 8221},
    {title: 'Japanese movies' , id: 10398},
    {title: 'Dutch movies' , id: 10606},
    {title: 'New Zealand movies' , id: 63782},
    {title: 'Russian movies' , id: 11567},
    {title: 'Scandinavian movies' , id: 9292},
    {title: 'Middle Eastern movies' , id: 5875},
    {title: 'Southeast Asian Movies' , id: 9196},
    {title: 'Eastern European movies' , id: 5254},
    {title: 'Turkish movies' , id: 1133133},
]},
{main: {title: "Music", id: 1701}, 
  sub: [
    {title: 'World music concerts' , id: 2856},
    {title: 'Rock & pop concerts' , id: 3278},
    {title: 'Urban & dance concerts' , id: 9472},
    {title: 'Kids music' , id: 52843},
    {title: 'Country & western/folk' , id: 1105},
    {title: 'Jazz & easy listening' , id: 10271},
    {title: 'Latin music' , id: 10741},
    {title: 'Musicals' , id: 13335},
    {title: 'Classic musicals' , id: 32392},
    {title: 'Disney musicals' , id: 59433},
    {title: 'Showbiz musicals' , id: 13573},
    {title: 'Stage musicals' , id: 55774},
]},
]